apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: kafkadata
  labels:
    app: kafkadata
spec:
  selector:
    matchLabels:
      app: kafkadata
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: kafkadata
        role: master
        tier: backend
    spec:
      containers:
      - name: kafkadata
        image: wurstmeister/kafka:2.12-2.2.0
        ports:
        - containerPort: 9092
        env:
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: "kafkadata:9092"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://kafkadata:9092"
          - name: KAFKA_CREATE_TOPICS
            value: "gmdatax-audit:1:1,gmdatax-replicationlog:1:1"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zk:2181"
---
apiVersion: v1
kind: Service
metadata:
  name: kafkadata
  labels:
    app: kafkadata
    role: master
    tier: backend
spec:
  ports:
  - port: 9092
    targetPort: 9092
  selector:
    app: kafkadata
    role: master
    tier: backend
