apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: zk
  labels:
    app: zk
spec:
  selector:
    matchLabels:
      app: zk
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: zk
        role: master
        tier: backend
    spec:
      containers:
      - name: zk
        image: wurstmeister/zookeeper
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: zk
  labels:
    app: zk
    role: master
    tier: backend
spec:
  ports:
  - port: 2181
    targetPort: 2181
  selector:
    app: zk
    role: master
    tier: backend
